# Generated by Django 4.2.6 on 2023-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.PositiveIntegerField(verbose_name='Isbn')),
                ('numero_paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('ano_escrita', models.PositiveIntegerField(verbose_name='Ano da Obra')),
            ],
        ),
    ]
