# Generated by Django 4.2.7 on 2023-11-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.PositiveIntegerField(verbose_name='ISBN'),
        ),
    ]
