# Generated by Django 4.2.6 on 2023-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livromodel_ano_escrita_alter_livromodel_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano_escrita',
            field=models.PositiveSmallIntegerField(verbose_name='Ano da Obra'),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='numero_paginas',
            field=models.PositiveIntegerField(verbose_name='Número de Páginas'),
        ),
    ]
