# Generated by Django 4.2.6 on 2023-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_livromodel_ano_escrita_alter_livromodel_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.PositiveIntegerField(max_length=13, verbose_name='ISBN'),
        ),
    ]
