# Generated by Django 4.2.6 on 2023-11-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_livromodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.PositiveIntegerField(verbose_name='ISBN'),
        ),
    ]
